from . import test_menu_is_reachable
from . import test_messaging
from . import test_the_create_desk
from . import test_sign_in
from . import test_stream_events
from . import test_a_change_replaces_the_table
from . import test_a_number_is_a_name_first
from . import test_the_system_fills_it_in_itself
from . import test_the_terms_of_use_are_agreed_to
